name: Action Sample Workflow

# Run workflow when a new pull request is openeds
on: 
  push:
    branches:
     - main
  discussion:
    types: [created]
jobs:
  check_user_permission:
    runs-on: ubuntu-latest
    name: A job to check user's permission level
    steps:
      # Check for write permission
      - name: Run only if user has sufficient permissions
        run: |
          'curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \ 
          -H "Authorization: Bearer <YOUR-TOKEN>" \
          https://api.github.com/repos/OWNER/REPO/deployments \
          -d '{"ref":"main","payload":"{ \"deploy\": \"migrate\" }","description":"Deploy request from hubot"}''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
